spring:
  application:
    name: restful
  profiles:
    default: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
timed:
  enabled: true
executor-service:
  fixed-repository-initialization:
    thread-number: 5
  scheduled-repository-initialization:
    refresh-interval: PT30M
limiter:
  kuda-go:
    max-concurrent-requests: 2


