resilience4j:
  circuitbreaker:
    instances:
      central-bank-client:
        sliding-window-size: 10
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: '5s'
        permitted-number-of-calls-in-half-open-state: 3
        minimum-number-of-calls: 5
springdoc:
  override-with-generic-response: false
client:
  currency:
    cb:
      url: 'https://www.cbr.ru/scripts/'
    cache:
      ttl: '3600000'
spring:
  application:
    name: currencies
